- pkg:maven/dev.opensavvy.gitlab/gitlab-ci-kotlin@0.3.1?classifier=sources
- pkg:maven/dev.opensavvy.gitlab/gitlab-ci-kotlin@0.4.0-rc.1?classifier=sources
- pkg:maven/dev.opensavvy.gitlab/gitlab-ci-kotlin@0.4.0?classifier=sources
- pkg:maven/dev.opensavvy.gitlab/gitlab-ci-kotlin@0.4.1?classifier=sources
- pkg:maven/dev.opensavvy.gitlab/gitlab-ci-kotlin@0.5.0?classifier=sources
- pkg:maven/dev.opensavvy.gitlab/gitlab-ci-kotlin@0.6.0?classifier=sources
