- pkg:maven/com.parrot.drone.groundsdk/groundsdk@1.8.0?classifier=sources
- pkg:maven/com.parrot.drone.groundsdk/groundsdk@1.8.1?classifier=sources
- pkg:maven/com.parrot.drone.groundsdk/groundsdk@7.0.0?classifier=sources
- pkg:maven/com.parrot.drone.groundsdk/groundsdk@7.0.1?classifier=sources
- pkg:maven/com.parrot.drone.groundsdk/groundsdk@7.1.0?classifier=sources
- pkg:maven/com.parrot.drone.groundsdk/groundsdk@7.2.0?classifier=sources
- pkg:maven/com.parrot.drone.groundsdk/groundsdk@7.3.0?classifier=sources
- pkg:maven/com.parrot.drone.groundsdk/groundsdk@7.4.0?classifier=sources
- pkg:maven/com.parrot.drone.groundsdk/groundsdk@7.5.0-rc1?classifier=sources
- pkg:maven/com.parrot.drone.groundsdk/groundsdk@7.5.0?classifier=sources
- pkg:maven/com.parrot.drone.groundsdk/groundsdk@7.5.1?classifier=sources
- pkg:maven/com.parrot.drone.groundsdk/groundsdk@7.5.2?classifier=sources
- pkg:maven/com.parrot.drone.groundsdk/groundsdk@7.6.0-rc1?classifier=sources
