- pkg:maven/io.github.mirko-felice.dronesecurity/user-application@1.0.1?classifier=sources
- pkg:maven/io.github.mirko-felice.dronesecurity/user-application@1.0.2?classifier=sources
- pkg:maven/io.github.mirko-felice.dronesecurity/user-application@1.0.3?classifier=sources
- pkg:maven/io.github.mirko-felice.dronesecurity/user-application@1.1.0?classifier=sources
- pkg:maven/io.github.mirko-felice.dronesecurity/user-application@1.2.0?classifier=sources
- pkg:maven/io.github.mirko-felice.dronesecurity/user-application@1.3.0?classifier=sources
- pkg:maven/io.github.mirko-felice.dronesecurity/user-application@1.3.1?classifier=sources
- pkg:maven/io.github.mirko-felice.dronesecurity/user-application@1.3.2?classifier=sources
- pkg:maven/io.github.mirko-felice.dronesecurity/user-application@1.3.3?classifier=sources
- pkg:maven/io.github.mirko-felice.dronesecurity/user-application@1.3.4?classifier=sources
- pkg:maven/io.github.mirko-felice.dronesecurity/user-application@1.3.5?classifier=sources
- pkg:maven/io.github.mirko-felice.dronesecurity/user-application@1.3.6?classifier=sources
